/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Hector Burgos
 */
public class MainView extends javax.swing.JFrame {
    
    

    /**
     * Creates new form RegistroEmpleadosView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        JPRegister = new javax.swing.JPanel();
        JBNewEmployed = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTEmployees = new javax.swing.JTable();
        JCBSort = new javax.swing.JComboBox<>();
        JBGenerateReport = new javax.swing.JButton();
        JLResults = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBNewEmployed.setText("+ Agregar empleado");

        JTEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTEmployees);

        JCBSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insercion", "Burbuja", "Mergesort", "Quicksort", "Shellsort", "Mezcla directa", "Mezcla equilibrada multiple" }));

        JBGenerateReport.setText("Generar reporte");

        JLResults.setText("Esperando operacion");

        javax.swing.GroupLayout JPRegisterLayout = new javax.swing.GroupLayout(JPRegister);
        JPRegister.setLayout(JPRegisterLayout);
        JPRegisterLayout.setHorizontalGroup(
            JPRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(JPRegisterLayout.createSequentialGroup()
                        .addComponent(JBNewEmployed)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPRegisterLayout.createSequentialGroup()
                        .addComponent(JCBSort, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBGenerateReport))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPRegisterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JLResults)))
                .addContainerGap())
        );
        JPRegisterLayout.setVerticalGroup(
            JPRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBNewEmployed)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(JPRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBGenerateReport)
                    .addComponent(JCBSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLResults)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    //Listeners de los botones
    public JButton listenJBNewEployed() {
        return JBNewEmployed;
    }
    
    public JButton listenJBGenerateReport() {
        return JBGenerateReport;
    }

    public JComboBox<String> listenJCBMSorter() {
        return JCBSort;
    }
    
    public JLabel listenJLResults() {
        return JLResults;
    }
    
    public JTable listenJTEmployees() {
        return JTEmployees;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBGenerateReport;
    public javax.swing.JButton JBNewEmployed;
    public javax.swing.JComboBox<String> JCBSort;
    public javax.swing.JLabel JLResults;
    private javax.swing.JPanel JPRegister;
    public javax.swing.JTable JTEmployees;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
